config/routes.rb
Rails.application.routes.draw do

  devise_for :members

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: :new_admin_session
    post 'admins/sign_in' => 'admins/sessions#create', as: :admin_session
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :members do
    resources :members, only: [:edit, :update, :show, :destroy]
    get 'cart_items' => 'cart_items#index', as: 'cart_items'

  	resources :cart_items, only: [:index, :create, :update, :destroy]
  	resource :cart_items, only: [:destroy]
    get 'orders/complete' => 'orders#complete', as: 'order_complete'
  	resources :orders, only: [:index, :new, :create, :show]
  	resources :shop_items, only: [:index, :show]
  	resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/new/confirm' => 'orders#confirm', as: 'order_confirm'
    get 'top' => 'shop_items#top', as: 'top'
    get 'about' => 'shop_items#about', as: 'about'
    get 'members/:id/edit/cancel' => 'members#cancel', as: 'cancel'
    put 'members/:id' => 'members#withdraw', as: 'withdraw_put'
    patch 'members/:id' => 'members#withdraw', as: 'withdraw_patch'
  end

    root 'members/shop_items#top'

  namespace :admins do
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
  	resources :shop_items, only: [:index, :new, :create, :show, :edit, :update]
  	resources :genres, only: [:index, :create, :edit, :update]
    get 'top' => 'orders#top', as: 'top'
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :shop_items, dependent: :destroy

  enum published_status: { 有効: 0, 無効: 1 }

  validates :name, presence: true

end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
  	#@genres = Genre.where(published_status: "有効")
    @genres = Genre.all.page(params[:page]).per(5)
  	@genre = Genre.new
  end

  def create
  	@genre = Genre.new(genre_params)
  	if @genre.save
  	  redirect_to admins_genres_path, notice: "ジャンル情報が登録されました"
    else
      @genres = Genre.all.page(params[:page])
      flash.now[:alert] = "#{@genre.errors.count}件のエラーが有ります"
      render "index"
    end
  end

  def edit
  	@genre = Genre.find(params[:id])
    #if @genre.published_status == "無効"
    #  redirect_to root_path
    #end
  end

  def update
  	@genre = Genre.find(params[:id])
  	if @genre.update(genre_params)
      redirect_to admins_genres_path, notice: "ジャンル情報が更新されました"
    else
      flash.now[:alert] = "#{@genre.errors.count}件のエラーが有ります"
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :published_status)
  end

end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admins/genres/_form.html.erb
<div class="container">

  <% if local_assigns[:edit_flag].present? %>
    <% temp = admins_genre_path(genre.id) %>
  <% else %>
    <% temp = admins_genres_path %>
  <% end %>

  <%= form_for(genre, url: temp, html: {class: "row"}) do |f| %>
    <div class="field col-4">
      <%= f.label :name, "ジャンル" %>
      <%= f.text_field :name %>
    </div>
    <div class="col-2">
      <%= f.radio_button :published_status, :有効, checked: "checked" %>
      <%= f.label :有効, class: "job_type_label" %>
    </div>
    <div class="col-2">
      <%= f.radio_button :published_status, :無効 %>
      <%= f.label :無効, class: "job_type_label" %>
    </div>
    <% if local_assigns[:edit_flag].present? %>
      <div class="action col-2">
        <%= f.submit "変更を保存", class: "btn btn-primary" %>
      </div>
    <% else %>
      <div class="action col-2">
        <%= f.submit "追加", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/admins/genres/edit.html.erb
<div class="container">

  <div class="row justify-content-start mt-3 mb-5">
    <h2 class="fa fa-star"> ジャンル編集画面</h2>
  </div>

  <%= render partial: "/layouts/error_messages", locals: { model: @genre } %>
  <%= render partial: 'form', locals: { genre: @genre, edit_flag: true } %>

</div>

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="row justify-content-start pt-3 mb-5">
    <h2 class="fa fa-star"> ジャンル追加・一覧画面</h2>
  </div>
  <%= render partial: "/layouts/error_messages", locals: { model: @genre } %>
  <%= render partial: 'form', locals: { genre: @genre } %>
  <table class="table table-hover table-inverse mt-3  bg-white">
    <thead class="thead-light">
      <tr>
        <th>ジャンルID</th>
        <th>ジャンル</th>
        <th>状態</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
        	<td><%= genre.id %></td>
          <td><%= genre.name %></td>
          <% if genre.published_status == "無効" %>
            <td><div class="btn btn-danger btn-sm active"><%= genre.published_status %></div></td>
          <% else %>
            <td><div class="btn btn-success btn-sm active"><%= genre.published_status %></div></td>
          <% end %>
          <td><%= link_to "編集する", edit_admins_genre_path(genre.id), class: "btn btn-primary btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row justify-content-center mt-3">
    <%= paginate @genres, class: "paginate" %>
  </div>
</div>