config/routes.rb
Rails.application.routes.draw do

  devise_for :members

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: :new_admin_session
    post 'admins/sign_in' => 'admins/sessions#create', as: :admin_session
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :members do
    resources :members, only: [:edit, :update, :show, :destroy]
    get 'cart_items' => 'cart_items#index', as: 'cart_items'

  	resources :cart_items, only: [:index, :create, :update, :destroy]
  	resource :cart_items, only: [:destroy]
    get 'orders/complete' => 'orders#complete', as: 'order_complete'
  	resources :orders, only: [:index, :new, :create, :show]
  	resources :shop_items, only: [:index, :show]
  	resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/new/confirm' => 'orders#confirm', as: 'order_confirm'
    get 'top' => 'shop_items#top', as: 'top'
    get 'about' => 'shop_items#about', as: 'about'
    get 'members/:id/edit/cancel' => 'members#cancel', as: 'cancel'
    put 'members/:id' => 'members#withdraw', as: 'withdraw_put'
    patch 'members/:id' => 'members#withdraw', as: 'withdraw_patch'
  end

    root 'members/shop_items#top'

  namespace :admins do
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
  	resources :shop_items, only: [:index, :new, :create, :show, :edit, :update]
  	resources :genres, only: [:index, :create, :edit, :update]
    get 'top' => 'orders#top', as: 'top'
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :shop_items, through: :cart_items

  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  acts_as_paranoid

  validates :last_name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角ひらがな・カタカナ・漢字で入力してください。" }
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "は全角カタカナで入力して下さい。" }
  validates :first_name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角ひらがな・カタカナ・漢字で入力してください。" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "は全角カタカナで入力して下さい。" }
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の整数で入力してください。" }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/, message: "は10〜11桁の整数で入力してください。" }

  def self.search(search)
    if search
      Member.where(["last_name LIKE? OR last_name_kana LIKE? OR first_name LIKE? OR first_name_kana LIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Member.all
    end
  end

end

app/controllers/admins/members_controller.rb
class Admins::MembersController < ApplicationController
    before_action :authenticate_admin!

    def index
	    @members = Member.with_deleted.search(params[:search])
      @members = @members.page(params[:page])
    end

    def show
	    @member = Member.with_deleted.find(params[:id])
    end

    def edit
	    @member = Member.with_deleted.find(params[:id])
    end

    def update
    	@member = Member.with_deleted.find(params[:id])
      #binding.pry
      if params[:member_status] == "2" && @member.deleted_at.blank?
        @member.destroy
      elsif params[:member_status] == "1" && @member.deleted_at.present?
        @member.restore
      end
      if @member.update(member_params)
        redirect_to admins_member_path(@member.id), notice: "会員情報が更新されました"
      else
        flash.now[:alert] = "#{@member.errors.count}件のエラーが有ります"
        render "edit"
      end
    end

    private
        def member_params
        params.require(:member).permit(:id,:first_name,:last_name,:first_name_kana,:last_name_kana,:address,:phone_number, :postal_code,:member_status, :email, :deleted_at)
    end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
    before_action :authenticate_admin!

	def top
		@orders = Order.all
		@today_orders_num = 0
		@orders.each do |order|
			if (order[:created_at].to_s.match(/#{Date.today.to_s}.+/))
				@today_orders_num = @today_orders_num + 1
			end
		end
	end

	def index
		if Member.where(id: params[:member_id]).present?
			@member = Member.find(params[:member_id])
			@orders = @member.orders
		elsif params[:mark].present?
			@orders = Order.where("created_at >= ? ", params[:mark])
		else
			@orders = Order.all
		end

		@path = Rails.application.routes.recognize_path(request.referer)

	    @before_controller = @path[:controller]
	    @before_action = @path[:action]

		@order_items = OrderItem.all
		@orders = @orders.page(params[:page])
		@members = Member.all
		@orders = @orders.page(params[:page])
	end

	def show
		@order = Order.find(params[:id])
		@order_items = OrderItem.all
		@order_item = @order.order_items
		@order.shipping_fee = 800

		@shop_items = ShopItem.all

		@members = Member.all
	end

	def update
	  	@order = Order.find(params[:id])
	  	@order_items = OrderItem.all
		@order_item = @order.order_items
		@num = @order_item.count
		@order.update(order_params)
		if @order.order_status == "入金確認"
	  		@order_item.each do |order_item|
				if order_item.production_status == "着手不可"
				    order_item.production_status = "製作待ち"
				    @order.update(order_params)
				else order_item.production_status == "製作中"
					@order.update(order_status: 2)
				end
			end
		elsif @order.order_status == "製作中"
			cooked_item = 0
			@order_item.each do |order_item|
				if order_item.production_status == "製作完了"
					cooked_item = cooked_item + 1
				    if cooked_item == @num
				    	@order.update(order_status: 3)
				    end
				end
			end
		end
	      redirect_to admins_order_path(@order)
  	end

  	private
    def order_params
    	params.require(:order).permit(:member_id, :payment_method, :name, :postal_code, :address, :order_status, :shipping_fee, order_items_attributes:[:id, :order_id, :shop_item_id, :quantity, :price, :production_status])
    end
end

app/controllers/members/cart_items_controller.rb
class Members::CartItemsController < ApplicationController
  before_action :authenticate_member!

  def index
  	@shop_items = current_member.shop_items
  	@cart_items = current_member.cart_items
  end

  def create
    if ShopItem.find(cart_item_params[:shop_item_id]).sale_status == "販売中"  #販売ステータスが"販売中"の商品の場合
      if CartItem.find_by(shop_item_id: cart_item_params[:shop_item_id]).blank?  #カート商品の中に重複している商品が無い場合
    	  @cart_item = CartItem.new(cart_item_params)
    	  @cart_item.member_id = current_member.id
        if @cart_item.save
          redirect_to members_cart_items_path, notice: "カートに商品が登録されました"
        else
          redirect_back fallback_location: root_path, alert: "カートに入れる商品の個数を選択してください"
        end
      elsif cart_item_params[:quantity].present?  #カートに追加する商品の個数が選択されている場合
        @cart_item = CartItem.find_by(shop_item_id: cart_item_params[:shop_item_id])
        @cart_item.quantity = @cart_item.quantity + cart_item_params[:quantity].to_i  #既存のカート商品個数に加算
        if @cart_item.save
          redirect_to members_cart_items_path, notice: "カート商品の個数・小計・合計金額が更新されました"
        else
          redirect_back fallback_location: root_path, alert: "カートに入れる商品の個数を選択してください"
        end
      else
        redirect_back fallback_location: root_path, alert: "カートに入れる商品の個数を選択してください"
      end
    end
  end

  def update
  	@cart_item = CartItem.find(params[:id])
  	if @cart_item.update(cart_item_params)
  	  redirect_to members_cart_items_path, notice: "カート商品の個数・小計・合計金額が更新されました"
    else
      redirect_to members_cart_items_path, alert: "個数は1以上の数字を入力してください"
    end
  end

  def destroy
  	if params[:id].present?  #カート商品のパラメータ(id)が存在する場合・・・カート商品単体の削除
      cart_item = CartItem.find(params[:id])
      cart_item.destroy
      redirect_to members_cart_items_path, notice: "カート商品が削除されました"
    else  #カート商品のパラメータ(id)が存在しない場合・・・カート商品全体の削除＝カートを空にする
      cart_items = CartItem.all
      cart_items.destroy_all
      redirect_to members_cart_items_path, notice: "カート商品が空になりました"
    end
  end

  private
  def cart_item_params
  	params.require(:cart_item).permit(:shop_item_id, :quantity)
  end

end

app/controllers/members/members_controller.rb
class Members::MembersController < ApplicationController
    before_action :authenticate_member!

    def edit
    	@member = Member.with_deleted.find(params[:id])
    end

    def update
        @member = Member.with_deleted.find(params[:id])
        if @member.update(member_params)
          redirect_to members_member_path(@member.id), notice: "会員情報が更新されました"
        else
          flash.now[:alert] = "#{@member.errors.count}件のエラーが有ります"
          render "edit"
        end
    end

    def show
    	@member = Member.with_deleted.find(params[:id])
    end

    def cancel
    	@member = Member.with_deleted.find(params[:id])
        if @member.deleted_at.present?
            redirect_to members_member_path(@member.id)
        end
    end

    def withdraw
        @member = Member.with_deleted.find(params[:id])
    end

    def destroy
        member = Member.find(params[:id]) #データ(レコード)を1件取得
        member.destroy #データ（レコード）を削除
        redirect_to members_top_path
    end

    private
        def member_params
        params.require(:member).permit(:id,:first_name,:last_name,:first_name_kana,:last_name_kana,:address,:phone_number, :postal_code,:member_status, :email, :deleted_at)
    end

end

app/controllers/members/orders_controller.rb
class Members::OrdersController < ApplicationController
    before_action :authenticate_member!

	def index
			@orders = Order.all
			@order = current_member.orders.page(params[:page]).per(4)
			@order_items = OrderItem.all

			@shop_items = ShopItem.all
	end

	def new
	    if current_member.cart_items.present?
  	        if current_member.shop_items.where(sale_status: "売切れ").blank? && Genre.where(id: current_member.shop_items.select(:genre_id), published_status: "無効").blank? && current_member.cart_items.present?  #カート商品の販売ステータス及びジャンルステータスが売切れ、無効でない場合
		        @order = Order.new
		        @order.member_id = current_member.id
		        @order.order_status = 0
		        @order.shipping_fee = 800
		        @shipping_addresses = ShippingAddress.all
    	    	@my_shipping_addresses = current_member.shipping_addresses
    	    	@new_shipping_address = ShippingAddress.new
  	        else
  	          redirect_to members_cart_items_path, alert: "大変申し訳ございません。売切れ商品がカートにございます。お手数ですが削除してから情報入力にお進みください。"
  	        end
	 	else
            redirect_to members_cart_items_path, alert: "カートは空の為、注文できません。"
	   	end
	end

	def create
		@cart_items = CartItem.all
		@cart_item = current_member.cart_items
		@shop_items = ShopItem.all
		@shop_item = current_member.shop_items
		@shipping_addresses = ShippingAddress.all
    	@my_shipping_addresses = current_member.shipping_addresses

		@order = Order.new(order_params)
		@order.member_id = current_member.id
		@order.order_status = "入金待ち"
		@order.shipping_fee = 800

		@new_shipping_address = ShippingAddress.new
		@new_shipping_address.member_id = current_member.id
        @new_shipping_address.postal_code = @order.postal_code
        @new_shipping_address.address = @order.address
        @new_shipping_address.name = @order.name

        @same_shipping_address = ShippingAddress.where(member_id: current_member.id).where(postal_code: @order.postal_code).where(address: @order.address).where(name: @order.name)
      	if @same_shipping_address.empty?
		    @new_shipping_address.save
		end

	    if current_member.cart_items.present?
		    if @order.save
	            redirect_to members_order_complete_path
	  	    else
	            flash.now[:alert] = "#{@order.errors.count}件のエラーが有ります"
	   	        render "new"
	 	    end
	 	else
            redirect_to members_cart_items_path, alert: "カートは空の為、注文できません。"
	   	end
	end

	def confirm
	    if current_member.cart_items.present?
		    @order = Order.new(order_params)
		    @order.order_status = "入金待ち"
		    @cart_items = CartItem.all
		    @cart_item = current_member.cart_items
		    @shop_items = ShopItem.all
		    @shop_item = current_member.shop_items

		    @new_shipping_address = ShippingAddress.new

    	    @my_shipping_addresses = current_member.shipping_addresses
    	    if order_params[:payment_method].blank? && @order.member_id.blank?
	 	      flash.now[:alert] = "支払方法、お届け先が入力されていません"
	 	      render "new"
    	    elsif @order.member_id.blank?
	 	      flash.now[:alert] = "お届け先が入力されていません"
	 	      render "new"
	 	    elsif @order.member_id == 333
	 	      @order.save
	 	      @order.errors.delete(:member)
	 	      if @order.errors.present?
	 	        flash.now[:alert] = "#{@order.errors.count}件のエラーが有ります"
	 	        render "new"
	 	      end
	 	    end
        else
            redirect_to members_cart_items_path, alert: "カートは空の為、注文できません。"
        end
	end

	def complete
		@cart_items = CartItem.all
		@cart_item = current_member.cart_items
		@cart_item.destroy_all
	end

	def show
		@order = Order.find(params[:id])
		@order_items = OrderItem.all
		@order_item = @order.order_items
		@order.shipping_fee = 800
		@cart_items = CartItem.all
		@cart_item = current_member.cart_items
		@shop_items = ShopItem.all
		@shop_item = current_member.shop_items
	end

	private
    def order_params
    	params.require(:order).permit(:member_id, :payment_method, :name, :postal_code, :address, :order_status, :shipping_fee, order_items_attributes:[:id, :order_id, :shop_item_id, :quantity, :price, :production_status])
    end

end

app/controllers/members/shipping_addresses_controller.rb
class Members::ShippingAddressesController < ApplicationController
  before_action :authenticate_member!

	def index
		@shipping_address = ShippingAddress.new
    @shipping_address.member_id = current_member.id
    @my_shipping_addresses = current_member.shipping_addresses.page(params[:page]).per(3)
	end

	def create
  	@shipping_address = ShippingAddress.new(shipping_address_params)
  	@shipping_address.member_id = current_member.id
    @my_shipping_addresses = current_member.shipping_addresses

    @same_shipping_address = ShippingAddress.where(member_id: current_member.id).where(postal_code: @shipping_address.postal_code).where(address: @shipping_address.address).where(name: @shipping_address.name)
    if @same_shipping_address.empty?
      if @shipping_address.save
        redirect_to members_shipping_addresses_path, notice: "配送先住所が新規登録されました"
      else
        flash.now[:alert] = "#{@shipping_address.errors.count}件のエラーが有ります"
        render "index"
      end
    elsif @same_shipping_address.present?
      flash.now[:alert] = "既に配送先住所に含まれております。"
      render "index"
 	  end
	end

  def edit
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def update
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.update(shipping_address_params)

    if @shipping_address.update(shipping_address_params)
      redirect_to members_shipping_addresses_path, notice: "配送先住所が編集されました"
    else
      flash.now[:alert] = "#{@shipping_address.errors.count}件のエラーが有ります"
      render "edit"
    end

  end

  def destroy
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.destroy
    redirect_to  members_shipping_addresses_path
  end


	private
  def shipping_address_params
  	params.require(:shipping_address).permit(:member_id, :name, :postal_code, :address)
  end
end

app/controllers/members/shop_items_controller.rb
class Members::ShopItemsController < ApplicationController

  def top
    #@genres = Genre.all
    @genres = Genre.where(published_status: "有効")  #ステータスが有効なジャンルのみ取得
    #@shop_items = ShopItem.all
    @shop_items = ShopItem.where(genre_id: @genres.ids)  #ステータスが有効なジャンルに紐付いた商品だけを取得
    @shop_items = @shop_items.page(params[:page])
  end

  def about
  end

  def index
    if Genre.where(id: params[:genre_id]).present?  #ジャンル検索フォームからlink_toで受け取ったパラメータのジャンルidがデータベースに存在する場合
      @genre = Genre.find(params[:genre_id])
      #@genres = Genre.all
      if @genre.published_status == "有効" #ジャンルステータスが有効の場合
        @genres = Genre.where(published_status: "有効")  #ステータスが有効なジャンルのみ取得
        @shop_items = @genre.shop_items  #ジャンルに紐付く商品を取得
        @shop_items = @shop_items.page(params[:page])
      else
        redirect_back fallback_location: root_path
      end
    else
      redirect_back fallback_location: root_path
    end
  end

  def show
    shop_item_genre_enable?  #application_controllerにて定義
    shop_item_enable?  #application_controllerにて定義
    #@genres = Genre.all
    @genres = Genre.where(published_status: "有効")  #ステータスが有効なジャンルのみ取得
    @cart_item = CartItem.new
  end

end

app/helpers/admins/members_helper.rb
module Admins::MembersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/members/cart_items_helper.rb
module Members::CartItemsHelper
end

app/helpers/members/members_helper.rb
module Members::MembersHelper
end

app/helpers/members/orders_helper.rb
module Members::OrdersHelper
end

app/helpers/members/post_images_helper.rb
module Members::PostImagesHelper
end

app/helpers/members/shipping_addresses_helper.rb
module Members::ShippingAddressesHelper
end

app/helpers/members/shop_items_helper.rb
module Members::ShopItemsHelper
end

app/views/members/orders/complete.html.erb
<div class="container">
    <div class="row">
    	<div class="col-12">
    		<div class="mx-auto" style="width: 400px;">
	    		<h5>ご購入ありがとうございました！</h5>
	    	</div>
    	</div>
    </div>
</div>

app/views/members/orders/confirm.html.erb
<div class="container">
    <h2 class="mt-3 mb-3 fas fa-file-invoice-dollar"> 注文情報確認</h2>
    <div class="row">
        <% idx_num = @order.shipping_fee %>
        <div class="col-7">
            <table class="table table-bordered bg-white">
                <thead class="thead-light">
                <tr>
                    <th>商品</th>
                    <th>単価（税込）</th>
                    <th>個数</th>
                    <th>小計</th>
                </tr>
                </thead>
                </<tbody>
                    <% cart_item_total_price = 0 %>
                    <% @shop_item.zip(@cart_item).each do |shop_item, cart_item| %>
                        <% shop_item_price_with_tax = (shop_item.price * 1.1).floor %>
                        <% cart_item_price = shop_item_price_with_tax * cart_item.quantity %>
                        <% cart_item_total_price = cart_item_total_price + cart_item_price %>
                        <tr>
                          <td><%= shop_item.name %></td>
                          <td><%= shop_item_price_with_tax.to_s(:delimited) %></td>
                          <td><%= cart_item.quantity %></td>
                          <td><%= cart_item_price.to_s(:delimited) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-5">
            <div class="col-7">
              <% @order.shipping_fee = 800 %>
              <table class="table table-bordered bg-white">
                <tr>
                  <th>配送料</th><td><%= @order.shipping_fee.to_s(:delimited) %>円</td>
                </tr>
                <tr>
                  <th>商品合計</th><td><%= cart_item_total_price.to_s(:delimited) %>円</td>
                </tr>
                <tr>
                  <th>請求金額</th><td><%= (cart_item_total_price + @order.shipping_fee).to_s(:delimited) %>円</td>
                </tr>
              </table>
            </div>
        </div>
        <div class="col-12">
            <h5>支払方法</h5>
            <div class="form-group" style="margin-left: 40px;">
                <%= @order.payment_method %>
            </div>
            <h5>お届け先</h5>
            <div class="form-group" style="margin-left: 40px;">
            <% if @order.member_id == 111 %>
                〒<%= @order.postal_code = "#{current_member.postal_code}" %> <%= @order.address = "#{current_member.address}" %><br>
                <%= @order.name = "#{current_member.last_name}#{current_member.first_name}" %>
            <% elsif @order.member_id == 222 %>
                <% @my_shipping_addresses.each.with_index(1) do |my_shipping_addresses_search, index| %>
                    <% if index == idx_num %>
                        <% @order.postal_code = my_shipping_addresses_search.postal_code %>
                        <% @order.address = my_shipping_addresses_search.address %>
                        <% @order.name = my_shipping_addresses_search.name %>
                        <% break %>
                    <% end %>
                <% end %>
                    〒<%= @order.postal_code %> <%= @order.address %><br>
                    <%= @order.name %>
            <% elsif @order.member_id == 333 %>
                〒<%= @order.postal_code %> <%= @order.address %><br>
                <%= @order.name %>
            <% else %>
            <% end %>
            <% @order.member_id = current_member.id %>
            <%= form_for(@order, url: members_orders_path) do |order| %>
                <%= order.hidden_field :member_id %>
                <%= order.hidden_field :payment_method %>
                <%= order.hidden_field :postal_code %>
                <%= order.hidden_field :address %>
                <%= order.hidden_field :name %>
                    <% @shop_item.zip(@cart_item).each do |shop_item, cart_item| %>
                        <%= order.fields_for :order_items, OrderItem.new do |order_item| %>
                          <%= order_item.hidden_field :order_id, :value => @order.id %>
                          <%= order_item.hidden_field :shop_item_id, :value => shop_item.id %>
                          <%= order_item.hidden_field :quantity, :value => cart_item.quantity %>
                          <%= order_item.hidden_field :price, :value => shop_item.price %>
                          <%= order_item.hidden_field :production_status, :value => "着手不可" %>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="col-12">
                <div class="mx-auto" style="width: 200px;">
                    <button type="submit" class="btn btn-outline-primary btn-lg btn-block" data-confirm="以下の内容で購入を確定してもよろしいですか？">購入を確定する</button>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/members/orders/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<h2 class="mt-3 mb-4 fas fa-history"> 注文履歴一覧</h2>
			<table class="table table-bordered bg-white">
				<thead class="thead-light">
					<tr>
						<th>注文日</th>
						<th>配送先</th>
						<th>注文商品</th>
						<th>支払金額</th>
						<th>ステータス</th>
						<th>注文詳細</th>
					</tr>
				</thead>
				<tbody>
					<% @order.each do |order| %>
						<tr>
							<td><%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
							<td><%= order.postal_code %><br><%= order.address %><br><%= order.name %></td>
							<td>
								<% @order_items.each do |order_item| %>
									<% if order_item.order_id == order.id %>
										<% shop_item_name = "" %>
										<% @shop_items.each do |shop_item| %>
											<% if shop_item.id == order_item.shop_item_id %>
												<% shop_item_name = "#{shop_item.name}" %>
												<% break %>
											<% else %>
												<% shop_item_name = "No" %>
											<% end %>
										<% end %>
										<%= shop_item_name %><br>
									<% end %>
								<% end %>
		                	</td>
							<td>
							<% order_item_total_price = 0 %>
							<% @order_items.each do |order_item| %>
								<% if order_item.order_id == order.id %>
							        <% order_item_price_with_tax = (order_item.price * 1.1).floor %>
							        <% order_item_price = order_item_price_with_tax * order_item.quantity %>
							        <% order_item_total_price = order_item_total_price + order_item_price %>
								<% end %>
							<% end %>
								<%= order_item_total_price + order.shipping_fee %>円</td>
							<td><%= order.order_status %></td>
							<td><%= link_to "表示する", members_order_path(order.id) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
    </div>
    <div class="row justify-content-center mt-3">
        <%= paginate @order, class: "pagination"  %>
    </div>
</div>

app/views/members/orders/new.html.erb
<div class="container">
    <div class="row">
        <%= render partial: "/layouts/error_messages", locals: { model: @order } %>
        <div class="col-6 ml-5 mt-3">
            <h2 class="fas fa-file-invoice-dollar"> 購入情報入力</h2>
            <%= form_for(@order, url: members_order_confirm_path, method: :get) do |order| %>
            <div class="form-group" style="margin-top: 30px;" >
                <h5>支払方法</h5>
                <div class="form-group" style="margin-left: 40px;" >
                    <%= order.radio_button :payment_method, "クレジットカード" %>クレジットカード<br>
                </div>
                <div class="form-group" style="margin-left: 40px;" >
                    <%= order.radio_button :payment_method, "銀行振込" %>銀行振込<br>
                </div>
            </div>
            <div class="form-group" style="margin-top: 30px;" >
                <h5>お届け先</h5>
                <div class="form-group" style="margin-left: 40px;">
                    <%= order.radio_button :member_id, 111 %>ご自身の住所<br>
                    <div class="form-group" style="margin-left: 40px;">
                        〒<%= current_member.postal_code %><%= current_member.address %><br><%= current_member.last_name %><%= current_member.first_name %>
                    </div>
                </div>
                <div class="form-group" style="margin-left: 40px; margin-top: 15px;" >
                    <%= order.radio_button :member_id, 222 %>登録済住所から選択する<br>
                    <div class="form-group" style="margin-left: 40px;">
                        <% @registered_addresses = @my_shipping_addresses.map.with_index(1) { |my_shipping_address, idx| "#{idx}：〒#{my_shipping_address.postal_code} #{my_shipping_address.address} #{my_shipping_address.name}" } %>
                        <%= order.select :shipping_fee, @registered_addresses %>
                    </div>
                </div>
                <div class="form-group" style="margin-left: 40px; margin-top: 15px;">
                    <%= order.radio_button :member_id, 333 %>新しいお届け先<br>
                    <div class="form-group" style="margin-left: 40px;">
                        <div class="form-group row">
                            <%= order.label :postal_code, "郵便番号", class: "col-3" %>
                            <%= order.text_field :postal_code, class: "col-4" %>
                        </div>
                    </div>
                    <div class="form-group" style="margin-left: 40px;">
                        <div class="form-group row">
                            <%= order.label :address, "住所", class: "col-3" %>
                            <%= order.text_field :address, class: "col-8" %>
                        </div>
                    </div>
                    <div class="form-group" style="margin-left: 40px;">
                        <div class="form-group row">
                            <%= order.label :name, "宛名", class: "col-3" %>
                            <%= order.text_field :name, class: "col-4" %>
                        </div>
                    </div>
                </div>
            </div>
                <button type="submit" class="btn btn-primary btn-block col-4 mx-auto" >確認画面に進む</button>
            <% end %>
        </div>
    </div>
</div>