config/routes.rb
Rails.application.routes.draw do

  devise_for :members

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: :new_admin_session
    post 'admins/sign_in' => 'admins/sessions#create', as: :admin_session
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :members do
    resources :members, only: [:edit, :update, :show, :destroy]
    get 'cart_items' => 'cart_items#index', as: 'cart_items'

  	resources :cart_items, only: [:index, :create, :update, :destroy]
  	resource :cart_items, only: [:destroy]
    get 'orders/complete' => 'orders#complete', as: 'order_complete'
  	resources :orders, only: [:index, :new, :create, :show]
  	resources :shop_items, only: [:index, :show]
  	resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/new/confirm' => 'orders#confirm', as: 'order_confirm'
    get 'top' => 'shop_items#top', as: 'top'
    get 'about' => 'shop_items#about', as: 'about'
    get 'members/:id/edit/cancel' => 'members#cancel', as: 'cancel'
    put 'members/:id' => 'members#withdraw', as: 'withdraw_put'
    patch 'members/:id' => 'members#withdraw', as: 'withdraw_patch'
  end

    root 'members/shop_items#top'

  namespace :admins do
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
  	resources :shop_items, only: [:index, :new, :create, :show, :edit, :update]
  	resources :genres, only: [:index, :create, :edit, :update]
    get 'top' => 'orders#top', as: 'top'
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :shop_items, through: :cart_items

  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  acts_as_paranoid

  validates :last_name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角ひらがな・カタカナ・漢字で入力してください。" }
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "は全角カタカナで入力して下さい。" }
  validates :first_name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角ひらがな・カタカナ・漢字で入力してください。" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "は全角カタカナで入力して下さい。" }
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の整数で入力してください。" }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/, message: "は10〜11桁の整数で入力してください。" }

  def self.search(search)
    if search
      Member.where(["last_name LIKE? OR last_name_kana LIKE? OR first_name LIKE? OR first_name_kana LIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Member.all
    end
  end

end

app/controllers/admins/members_controller.rb
class Admins::MembersController < ApplicationController
    before_action :authenticate_admin!

    def index
	    @members = Member.with_deleted.search(params[:search])
      @members = @members.page(params[:page])
    end

    def show
	    @member = Member.with_deleted.find(params[:id])
    end

    def edit
	    @member = Member.with_deleted.find(params[:id])
    end

    def update
    	@member = Member.with_deleted.find(params[:id])
      #binding.pry
      if params[:member_status] == "2" && @member.deleted_at.blank?
        @member.destroy
      elsif params[:member_status] == "1" && @member.deleted_at.present?
        @member.restore
      end
      if @member.update(member_params)
        redirect_to admins_member_path(@member.id), notice: "会員情報が更新されました"
      else
        flash.now[:alert] = "#{@member.errors.count}件のエラーが有ります"
        render "edit"
      end
    end

    private
        def member_params
        params.require(:member).permit(:id,:first_name,:last_name,:first_name_kana,:last_name_kana,:address,:phone_number, :postal_code,:member_status, :email, :deleted_at)
    end

end

app/controllers/members/cart_items_controller.rb
class Members::CartItemsController < ApplicationController
  before_action :authenticate_member!

  def index
  	@shop_items = current_member.shop_items
  	@cart_items = current_member.cart_items
  end

  def create
    if ShopItem.find(cart_item_params[:shop_item_id]).sale_status == "販売中"  #販売ステータスが"販売中"の商品の場合
      if CartItem.find_by(shop_item_id: cart_item_params[:shop_item_id]).blank?  #カート商品の中に重複している商品が無い場合
    	  @cart_item = CartItem.new(cart_item_params)
    	  @cart_item.member_id = current_member.id
        if @cart_item.save
          redirect_to members_cart_items_path, notice: "カートに商品が登録されました"
        else
          redirect_back fallback_location: root_path, alert: "カートに入れる商品の個数を選択してください"
        end
      elsif cart_item_params[:quantity].present?  #カートに追加する商品の個数が選択されている場合
        @cart_item = CartItem.find_by(shop_item_id: cart_item_params[:shop_item_id])
        @cart_item.quantity = @cart_item.quantity + cart_item_params[:quantity].to_i  #既存のカート商品個数に加算
        if @cart_item.save
          redirect_to members_cart_items_path, notice: "カート商品の個数・小計・合計金額が更新されました"
        else
          redirect_back fallback_location: root_path, alert: "カートに入れる商品の個数を選択してください"
        end
      else
        redirect_back fallback_location: root_path, alert: "カートに入れる商品の個数を選択してください"
      end
    end
  end

  def update
  	@cart_item = CartItem.find(params[:id])
  	if @cart_item.update(cart_item_params)
  	  redirect_to members_cart_items_path, notice: "カート商品の個数・小計・合計金額が更新されました"
    else
      redirect_to members_cart_items_path, alert: "個数は1以上の数字を入力してください"
    end
  end

  def destroy
  	if params[:id].present?  #カート商品のパラメータ(id)が存在する場合・・・カート商品単体の削除
      cart_item = CartItem.find(params[:id])
      cart_item.destroy
      redirect_to members_cart_items_path, notice: "カート商品が削除されました"
    else  #カート商品のパラメータ(id)が存在しない場合・・・カート商品全体の削除＝カートを空にする
      cart_items = CartItem.all
      cart_items.destroy_all
      redirect_to members_cart_items_path, notice: "カート商品が空になりました"
    end
  end

  private
  def cart_item_params
  	params.require(:cart_item).permit(:shop_item_id, :quantity)
  end

end

app/controllers/members/members_controller.rb
class Members::MembersController < ApplicationController
    before_action :authenticate_member!

    def edit
    	@member = Member.with_deleted.find(params[:id])
    end

    def update
        @member = Member.with_deleted.find(params[:id])
        if @member.update(member_params)
          redirect_to members_member_path(@member.id), notice: "会員情報が更新されました"
        else
          flash.now[:alert] = "#{@member.errors.count}件のエラーが有ります"
          render "edit"
        end
    end

    def show
    	@member = Member.with_deleted.find(params[:id])
    end

    def cancel
    	@member = Member.with_deleted.find(params[:id])
        if @member.deleted_at.present?
            redirect_to members_member_path(@member.id)
        end
    end

    def withdraw
        @member = Member.with_deleted.find(params[:id])
    end

    def destroy
        member = Member.find(params[:id]) #データ(レコード)を1件取得
        member.destroy #データ（レコード）を削除
        redirect_to members_top_path
    end

    private
        def member_params
        params.require(:member).permit(:id,:first_name,:last_name,:first_name_kana,:last_name_kana,:address,:phone_number, :postal_code,:member_status, :email, :deleted_at)
    end

end

app/controllers/members/orders_controller.rb
class Members::OrdersController < ApplicationController
    before_action :authenticate_member!

	def index
			@orders = Order.all
			@order = current_member.orders.page(params[:page]).per(4)
			@order_items = OrderItem.all

			@shop_items = ShopItem.all
	end

	def new
	    if current_member.cart_items.present?
  	        if current_member.shop_items.where(sale_status: "売切れ").blank? && Genre.where(id: current_member.shop_items.select(:genre_id), published_status: "無効").blank? && current_member.cart_items.present?  #カート商品の販売ステータス及びジャンルステータスが売切れ、無効でない場合
		        @order = Order.new
		        @order.member_id = current_member.id
		        @order.order_status = 0
		        @order.shipping_fee = 800
		        @shipping_addresses = ShippingAddress.all
    	    	@my_shipping_addresses = current_member.shipping_addresses
    	    	@new_shipping_address = ShippingAddress.new
  	        else
  	          redirect_to members_cart_items_path, alert: "大変申し訳ございません。売切れ商品がカートにございます。お手数ですが削除してから情報入力にお進みください。"
  	        end
	 	else
            redirect_to members_cart_items_path, alert: "カートは空の為、注文できません。"
	   	end
	end

	def create
		@cart_items = CartItem.all
		@cart_item = current_member.cart_items
		@shop_items = ShopItem.all
		@shop_item = current_member.shop_items
		@shipping_addresses = ShippingAddress.all
    	@my_shipping_addresses = current_member.shipping_addresses

		@order = Order.new(order_params)
		@order.member_id = current_member.id
		@order.order_status = "入金待ち"
		@order.shipping_fee = 800

		@new_shipping_address = ShippingAddress.new
		@new_shipping_address.member_id = current_member.id
        @new_shipping_address.postal_code = @order.postal_code
        @new_shipping_address.address = @order.address
        @new_shipping_address.name = @order.name

        @same_shipping_address = ShippingAddress.where(member_id: current_member.id).where(postal_code: @order.postal_code).where(address: @order.address).where(name: @order.name)
      	if @same_shipping_address.empty?
		    @new_shipping_address.save
		end

	    if current_member.cart_items.present?
		    if @order.save
	            redirect_to members_order_complete_path
	  	    else
	            flash.now[:alert] = "#{@order.errors.count}件のエラーが有ります"
	   	        render "new"
	 	    end
	 	else
            redirect_to members_cart_items_path, alert: "カートは空の為、注文できません。"
	   	end
	end

	def confirm
	    if current_member.cart_items.present?
		    @order = Order.new(order_params)
		    @order.order_status = "入金待ち"
		    @cart_items = CartItem.all
		    @cart_item = current_member.cart_items
		    @shop_items = ShopItem.all
		    @shop_item = current_member.shop_items

		    @new_shipping_address = ShippingAddress.new

    	    @my_shipping_addresses = current_member.shipping_addresses
    	    if order_params[:payment_method].blank? && @order.member_id.blank?
	 	      flash.now[:alert] = "支払方法、お届け先が入力されていません"
	 	      render "new"
    	    elsif @order.member_id.blank?
	 	      flash.now[:alert] = "お届け先が入力されていません"
	 	      render "new"
	 	    elsif @order.member_id == 333
	 	      @order.save
	 	      @order.errors.delete(:member)
	 	      if @order.errors.present?
	 	        flash.now[:alert] = "#{@order.errors.count}件のエラーが有ります"
	 	        render "new"
	 	      end
	 	    end
        else
            redirect_to members_cart_items_path, alert: "カートは空の為、注文できません。"
        end
	end

	def complete
		@cart_items = CartItem.all
		@cart_item = current_member.cart_items
		@cart_item.destroy_all
	end

	def show
		@order = Order.find(params[:id])
		@order_items = OrderItem.all
		@order_item = @order.order_items
		@order.shipping_fee = 800
		@cart_items = CartItem.all
		@cart_item = current_member.cart_items
		@shop_items = ShopItem.all
		@shop_item = current_member.shop_items
	end

	private
    def order_params
    	params.require(:order).permit(:member_id, :payment_method, :name, :postal_code, :address, :order_status, :shipping_fee, order_items_attributes:[:id, :order_id, :shop_item_id, :quantity, :price, :production_status])
    end

end

app/controllers/members/shipping_addresses_controller.rb
class Members::ShippingAddressesController < ApplicationController
  before_action :authenticate_member!

	def index
		@shipping_address = ShippingAddress.new
    @shipping_address.member_id = current_member.id
    @my_shipping_addresses = current_member.shipping_addresses.page(params[:page]).per(3)
	end

	def create
  	@shipping_address = ShippingAddress.new(shipping_address_params)
  	@shipping_address.member_id = current_member.id
    @my_shipping_addresses = current_member.shipping_addresses

    @same_shipping_address = ShippingAddress.where(member_id: current_member.id).where(postal_code: @shipping_address.postal_code).where(address: @shipping_address.address).where(name: @shipping_address.name)
    if @same_shipping_address.empty?
      if @shipping_address.save
        redirect_to members_shipping_addresses_path, notice: "配送先住所が新規登録されました"
      else
        flash.now[:alert] = "#{@shipping_address.errors.count}件のエラーが有ります"
        render "index"
      end
    elsif @same_shipping_address.present?
      flash.now[:alert] = "既に配送先住所に含まれております。"
      render "index"
 	  end
	end

  def edit
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def update
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.update(shipping_address_params)

    if @shipping_address.update(shipping_address_params)
      redirect_to members_shipping_addresses_path, notice: "配送先住所が編集されました"
    else
      flash.now[:alert] = "#{@shipping_address.errors.count}件のエラーが有ります"
      render "edit"
    end

  end

  def destroy
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.destroy
    redirect_to  members_shipping_addresses_path
  end


	private
  def shipping_address_params
  	params.require(:shipping_address).permit(:member_id, :name, :postal_code, :address)
  end
end

app/controllers/members/shop_items_controller.rb
class Members::ShopItemsController < ApplicationController

  def top
    #@genres = Genre.all
    @genres = Genre.where(published_status: "有効")  #ステータスが有効なジャンルのみ取得
    #@shop_items = ShopItem.all
    @shop_items = ShopItem.where(genre_id: @genres.ids)  #ステータスが有効なジャンルに紐付いた商品だけを取得
    @shop_items = @shop_items.page(params[:page])
  end

  def about
  end

  def index
    if Genre.where(id: params[:genre_id]).present?  #ジャンル検索フォームからlink_toで受け取ったパラメータのジャンルidがデータベースに存在する場合
      @genre = Genre.find(params[:genre_id])
      #@genres = Genre.all
      if @genre.published_status == "有効" #ジャンルステータスが有効の場合
        @genres = Genre.where(published_status: "有効")  #ステータスが有効なジャンルのみ取得
        @shop_items = @genre.shop_items  #ジャンルに紐付く商品を取得
        @shop_items = @shop_items.page(params[:page])
      else
        redirect_back fallback_location: root_path
      end
    else
      redirect_back fallback_location: root_path
    end
  end

  def show
    shop_item_genre_enable?  #application_controllerにて定義
    shop_item_enable?  #application_controllerにて定義
    #@genres = Genre.all
    @genres = Genre.where(published_status: "有効")  #ステータスが有効なジャンルのみ取得
    @cart_item = CartItem.new
  end

end

app/helpers/admins/members_helper.rb
module Admins::MembersHelper
end

app/helpers/members/cart_items_helper.rb
module Members::CartItemsHelper
end

app/helpers/members/members_helper.rb
module Members::MembersHelper
end

app/helpers/members/orders_helper.rb
module Members::OrdersHelper
end

app/helpers/members/post_images_helper.rb
module Members::PostImagesHelper
end

app/helpers/members/shipping_addresses_helper.rb
module Members::ShippingAddressesHelper
end

app/helpers/members/shop_items_helper.rb
module Members::ShopItemsHelper
end

app/views/members/members/cancel.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">

      <h2 class="mt-5 mb-5" style="text-align:center;">本当に退会しますか？</h2>

    <p style="text-align: center;">
      退会すると、会員登録情報や<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      退会する場合は『退会する』をクリックしてください。
      </p>

     <div class="form-body">
        <%= form_for(@member, url: members_member_path, method: :delete) do |f| %>

             <div class="actions" style="text-align:center;">
                  <%= f.submit "退会する", class: "btn btn-danger" %>
                  <%= link_to "退会しない",members_member_path(@member.id), class: "btn btn-primary" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/members/members/edit.html.erb
<div class="box">

<h2 class="fas fa-user" style="margin: 28px; width:250px; display: inline-block;"> 会員編集画面</h2> <%= link_to"退会する", members_cancel_path, class: "btn btn-danger" ,style:"margin-bottom:10px;"%>

    <%= render partial: "/layouts/error_messages", locals: { model: @member } %>

    <div class="form-body">
        <%= form_for(@member, url: members_member_path) do |f| %>
            <div style="margin-left: 28px;">
                <table align="28" border="1" width="700" cellspacing="0" cellpadding="5" bordercolor="#333333" background: rgba="(0,0,0,0.5)" >

                    <tr>
                        <td style="background: rgba(0,0,0,0.2);" align="left" nowrap><%= f.label :氏名 %></td>
                        <td  valign="top" width="500"><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
                    </tr>

                    <tr>
                        <td style="background: rgba(0,0,0,0.2);" align="left" nowrap>カナ</td>
                        <td  valign="top" width="500"><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
                    </tr>

                    <tr>
                        <td style="background: rgba(0,0,0,0.2);" align="left" nowrap>郵便番号</td>
                        <td  valign="top" width="500"><%= f.text_field :postal_code %></td>
                    </tr>

                    <tr>
                        <td style="background: rgba(0,0,0,0.2);" align="left" nowrap>住所</td>
                        <td  valign="top" width="500"><%= f.text_field :address %></td>
                    </tr>

                    <tr>
                        <td style="background: rgba(0,0,0,0.2);" align="left" nowrap>電話番号</td>
                        <td  valign="top" width="500"><%= f.text_field :phone_number %></td>
                    </tr>

                    <tr>
                        <td style="background: rgba(0,0,0,0.2);" align="left" nowrap>メールアドレス</td>
                        <td  valign="top" width="500"><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
                    </tr>
                </table>
            </div>
            <div class="actions" style="margin: 30px;">
                <%= f.submit "編集内容を保存する", class: "btn btn-primary" ,style:"margin-left: 160px;" %>
            </div>
        <% end %>
    </div>
</div>

app/views/members/members/show.html.erb
<div class="box mt-2">


    <h2 style="padding: 10px 0px 0px 28px;" class="fas fa-user"> マイページ</h2>




    <h5 style="padding: 20px 0px 10px 28px;">登録情報</h5>
    <div style="padding: 0px 0px 20px 28px ;"><%= link_to"編集する", edit_members_member_path(@member.id), class: "btn btn-primary"  %>
	    <button style="margin: 10px;" class="btn btn-primary">パスワードを変更する</button>
    </div>
        <div style="margin-left: 28px;">
            <table align="28" border="1" width="700" cellspacing="0" cellpadding="5" bordercolor="#333333">

                <tr>
                    <td bgcolor="#d3d3d3" align="left" nowrap>氏名</td>
                        <td bgcolor="#FFFFFF" valign="top" width="500"><%= @member.last_name %><%= @member.first_name %></td>
                </tr>

                    <tr>
                        <td bgcolor="#d3d3d3" align="left" nowrap>フリガナ</td>
                        <td bgcolor="#FFFFFF" valign="top" width="500"><%= @member.last_name_kana %><%= @member.first_name_kana %></td>
                    </tr>

                        <tr>
                            <td bgcolor="#d3d3d3" align="left" nowrap>郵便番号</td>
                            <td bgcolor="#FFFFFF" valign="top" width="500"><%= @member.postal_code %></td>
                        </tr>

                            <tr>
                                <td bgcolor="#d3d3d3" align="left" nowrap>住所</td>
                                <td bgcolor="#FFFFFF" valign="top" width="500"><%= @member.address %></td>
                            </tr>

                            <tr>
                                <td bgcolor="#d3d3d3" align="left" nowrap>電話番号</td>
                                <td bgcolor="#FFFFFF" valign="top" width="500"><%= @member.phone_number %></td>
                            </tr>



                                <tr>
                                    <td bgcolor="#d3d3d3" align="left" nowrap>メールアドレス</td>
                                    <td bgcolor="#FFFFFF" valign="top" width="500"><%= @member.email %></td>
                                </tr>
            </table>
        </div>

            <h5 style="margin: 28px;">配送先   <%= link_to"一覧を見る", members_shipping_addresses_path, class: "btn btn-primary" ,style:"margin-left:18px;" %></h5>
            <h5 style="margin: 28px;">注文履歴  <%= link_to"一覧を見る", members_orders_path, class: "btn btn-primary" %></h5>

<br>
</div>