config/routes.rb
Rails.application.routes.draw do

  devise_for :members

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: :new_admin_session
    post 'admins/sign_in' => 'admins/sessions#create', as: :admin_session
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :members do
    resources :members, only: [:edit, :update, :show, :destroy]
    get 'cart_items' => 'cart_items#index', as: 'cart_items'

  	resources :cart_items, only: [:index, :create, :update, :destroy]
  	resource :cart_items, only: [:destroy]
    get 'orders/complete' => 'orders#complete', as: 'order_complete'
  	resources :orders, only: [:index, :new, :create, :show]
  	resources :shop_items, only: [:index, :show]
  	resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/new/confirm' => 'orders#confirm', as: 'order_confirm'
    get 'top' => 'shop_items#top', as: 'top'
    get 'about' => 'shop_items#about', as: 'about'
    get 'members/:id/edit/cancel' => 'members#cancel', as: 'cancel'
    put 'members/:id' => 'members#withdraw', as: 'withdraw_put'
    patch 'members/:id' => 'members#withdraw', as: 'withdraw_patch'
  end

    root 'members/shop_items#top'

  namespace :admins do
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
  	resources :shop_items, only: [:index, :new, :create, :show, :edit, :update]
  	resources :genres, only: [:index, :create, :edit, :update]
    get 'top' => 'orders#top', as: 'top'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :member
  belongs_to :shop_item

  validates :shop_item_id, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :shop_items, dependent: :destroy

  enum published_status: { 有効: 0, 無効: 1 }

  validates :name, presence: true

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :shop_items, through: :cart_items

  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  acts_as_paranoid

  validates :last_name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角ひらがな・カタカナ・漢字で入力してください。" }
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "は全角カタカナで入力して下さい。" }
  validates :first_name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角ひらがな・カタカナ・漢字で入力してください。" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "は全角カタカナで入力して下さい。" }
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の整数で入力してください。" }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/, message: "は10〜11桁の整数で入力してください。" }

  def self.search(search)
    if search
      Member.where(["last_name LIKE? OR last_name_kana LIKE? OR first_name LIKE? OR first_name_kana LIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Member.all
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items

  enum order_status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

  validates :payment_method, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の整数で入力してください。" }
  validates :address, presence: true
  validates :name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角ひらがな・カタカナ・漢字で入力してください。" }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :shop_item

  enum production_status:{着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

  #validates :order_id, presence: true
  validates :shop_item_id, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :price, presence: true
  validates :production_status, presence: true

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :member

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "は7桁の整数で入力してください。" }
  validates :address, presence: true
  validates :name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "は全角ひらがな・カタカナ・漢字で入力してください。" }

end

app/models/shop_item.rb
class ShopItem < ApplicationRecord

  belongs_to :genre
  has_many :order_items, dependent: :destroy

  has_many :cart_items, dependent: :destroy
  has_many :members, through: :cart_items

  enum sale_status: { 販売中: 0, 売切れ: 1 }

  attachment :image

  validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :sale_status, presence: true

  def self.search(search)
    if search
      ShopItem.where(["name LIKE ?", "%#{search}%"])
    else
      ShopItem.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Admin
        admins_top_path
      when Member
        members_top_path
      end
  end

  def after_sign_out_path_for(resource)
    new_member_session_path
  end

  def shop_item_genre_enable?  #取得した商品に紐づくジャンルステータスが無効な場合rootへ遷移
    @shop_item = ShopItem.find(params[:id])
    @genre = Genre.find(@shop_item.genre_id)
    if @genre.published_status == "無効"
      redirect_to root_path
    end
  end

  def shop_item_enable?  #取得した商品の販売ステータスが販売停止中の場合rootへ遷移
    @shop_item = ShopItem.find(params[:id])
    if @shop_item.sale_status == "販売停止中"
      redirect_to root_path
    end
  end

  protected
  def configure_permitted_parameters
    added_attrs = [ :member_status, :email, :password, :password_confirmation, :last_name, :first_name, :last_name_kana, :first_name_kana,:postal_code, :address, :phone_number]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/members_helper.rb
module Admins::MembersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/shop_items_helper.rb
module Admins::ShopItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members/cart_items_helper.rb
module Members::CartItemsHelper
end

app/helpers/members/members_helper.rb
module Members::MembersHelper
end

app/helpers/members/orders_helper.rb
module Members::OrdersHelper
end

app/helpers/members/post_images_helper.rb
module Members::PostImagesHelper
end

app/helpers/members/shop_items_helper.rb
module Members::ShopItemsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="col-12 alert alert-warning pl-5">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/6bb1565f31.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top">
      <div class="container-fruid">
        <nav class="nav navbar-nav">
          <a class="navbar-brand" href="/"><span class="title">ながのCAKE</span></a>
          <ul class="nav">
            <% url_array = request.url.split('/') %>
            <% if url_array[3] == "members" ||  url_array[3].blank? %>
                  <li class="mx-3"><%= link_to 'トップ', members_top_path, class: "nav-link fas fa-store" %></li>
                  <li class="mx-3"><%= link_to 'アバウト', members_about_path, class: "nav-link fas fa-birthday-cake" %></li>

                <% if member_signed_in? %>
                  <li class="mx-3"><%= link_to 'カート', members_cart_items_path, class: "nav-link fas fa-shopping-cart" %></li>
                  <li class="mx-3"><%= link_to "#{current_member.last_name}" + "#{current_member.first_name}", members_member_path(current_member.id), class: "nav-link fas fa-user" %></li>
                  <li class="mx-3"><%= link_to 'ログアウト', destroy_member_session_path, class: "nav-link fas fa-sign-out-alt", method: :delete %></li>

                <% else %>
                  <li class="mx-3"><%= link_to '会員登録', new_member_registration_path, class: "nav-link fas fa-edit" %></li>
                  <li class="mx-3"><%= link_to 'ログイン', new_member_session_path, class: "nav-link fas fa-sign-in-alt" %></li>
                <% end %>

            <% elsif url_array[3] == "admins" %>
                <% if admin_signed_in? %>
                  <li class="mx-3"><%= link_to 'トップ', admins_top_path, class: "nav-link fas fa-home" %></li>
                  <li class="mx-3"><%= link_to '商品一覧', admins_shop_items_path, class: "nav-link fas fa-store" %></li>
                  <li class="mx-3"><%= link_to 'ジャンル一覧', admins_genres_path, class: "nav-link fas fa-star" %></li>
                  <li class="mx-3"><%= link_to '注文履歴一覧', admins_orders_path, class: "nav-link fas fa-history" %></li>
                  <li class="mx-3"><%= link_to '会員一覧', admins_members_path, class: "nav-link fas fa-user" %></li>
                  <li class="mx-3"><%= link_to '管理者ログアウト', destroy_admin_session_path, class: "nav-link fas fa-sign-out-alt", method: :delete %></li>
                  <%= form_tag(admins_members_path, method: :get, class: "form-inline my-2 my-lg-0 ml-auto") do %>
                    <%= text_field_tag :search, '', placeholder: "名前を入力...", class: "form-control mr-sm-2" %>
                    <%= content_tag :button, "会員検索", formaction: admins_members_path, class: "btn btn-sm btn-outline-success my-2 my-sm-0 mr-1" %>
                    <%= content_tag :button, "商品検索", formaction: admins_shop_items_path, class: "btn btn-sm btn-outline-success my-2 my-sm-0" %>
                  <% end %>
                <% else %>
                  <li class="mx-3"><%= link_to '管理者ログイン', new_admin_session_path, class: "nav-link fas fa-sign-in-alt" %></li>
                  <li class="mx-3 nav-link" style="color: red;">管理者ログイン未済</li>
                <% end %>
            <% else %>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <% unless notice.nil? %>
      <p id="notice" class="alert alert-success">
        <%= notice %>
      </p>
    <% end %>
    <% unless alert.nil? %>
      <p id="alert" class="alert alert-warning">
        <%= alert %>
      </p>
    <% end %>

    <div class="p-1">
      <div class="main-body">
        <%= yield %>
      </div>
    </div>

  </body>
</html>